server:
  port: 8999
eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: discount-data
          uri: lb://discount-data
          predicates:
            - Path=/discount/**
        - id: tariff-data
          uri: lb://tariff-data
          predicates:
            - Path=/tariffdata/**